# Generated by Django 5.0 on 2023-12-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract_Type',
            new_name='ContractType',
        ),
        migrations.RenameModel(
            old_name='Job_Position',
            new_name='JobPosition',
        ),
        migrations.RenameModel(
            old_name='Service_Records',
            new_name='ServiceRecord',
        ),
    ]
